name: snippets
version: 1.0.0
author: Flutter Team <flutter-dev@googlegroups.com>
description: A code snippet dartdoc extension for Flutter API docs.
homepage: https://github.com/flutter/flutter

environment:
  sdk: ">=2.12.1 <3.0.0"

dartdoc:
  nodoc: true

dependencies:
  recase: ^4.0.0-nullsafety.0
  args: ^2.0.0
  dart_style: ^2.0.0
  meta: ^1.3.0
  platform: ^3.0.0
  process: ^4.1.1
  analyzer: ^1.2.0
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.8

executables:
  snippets: bin/main.dart


